### ISSUE TITLE
[Compatibility suggestion] Open Parties and Claims

### ISSUE THREAD

**Issue by DadoIrie** [AmibeSkyfy16/TinyEconomyRenewed#3]
A optional compatibility feature with [Open Parties and Claims](https://modrinth.com/mod/open-parties-and-claims) would perfectly fit into this one. Any chance for it?

UPDATE: I might was too fast asking that, because as far as I know there is no per player claims count. It is done with ranks how many claims a rank can have.

**Comment by AmibeSkyfy16** [comment]
Hmm for the moment no, I'm leaving the computer world at the moment, I'm just updating some mod, that's all :(
